version: 2

aliases:
  - &install-cmake
    run:
      name: Install CMake
      command: sudo apt-get install cmake
  - &install-linguist
    run:
      name: Install github-linguist
      command: gem install github-linguist
  - &run-linguist
    run:
      name: Run github-linguist on repository
      command: linguist
  - &generate-html-chart
    run:
      name: Run script that generates html chart file
      command: ./chart.sh
  - &install-node
    run:
      name: Install NodeJS
      command: sudo apt-get install node
  - &install-puppeteer
    run:
      name: Install Puppeteer
      command: npm i puppeteer
  - &html2png
    run:
      name: Convert html chart to png
      command: ./html2png.sh



defaults: &defaults
  docker:
    - image: circleci/ruby

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - <<: *install-cmake
      - <<: *install-linguist
      - <<: *run-linguist
      - <<: *generate-html-chart
      - <<: *install-node
      - <<: *install-puppeteer
      - <<: *html2png