version: 2

aliases:
  - &install-cmake
    run:
      name: Install CMake
      command: sudo apt-get install cmake
  - &install-linguist
    run:
      name: Install github-linguist
      command: gem install github-linguist
  - &run-linguist
    run:
      name: Run github-linguist on repository
      command: linguist
  - &generate-html-chart
    run:
      name: Run script that generates html chart file
      command: ./chart.sh
  - &install-node
    run:
      name: Install NodeJS
      command: |
        curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
        sudo apt-get install -y nodejs
  - &install-puppeteer
    run:
      name: Install Puppeteer
      command: npm i puppeteer
  - &html2png
    run:
      name: Convert html chart to png
      command: ./html2png.sh
  - &move-chart-files
    run:
      name: Moving generated files to artifacts directory
      command: mv chart.html /tmp/ && mv chart.png /tmp/
  - &store-artifacts
    store_artifacts:
      path: /tmp/

defaults: &defaults
  docker:
    - image: circleci/ruby

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - <<: *install-cmake
      - <<: *install-linguist
      - <<: *run-linguist
      - <<: *generate-html-chart
      - <<: *install-node
      - <<: *install-puppeteer
      - <<: *html2png
      - <<: *move-chart-files
      - <<: *store-artifacts