version: 2

aliases:
  - &install-cmake
    run:
      name: Install CMake
      command: sudo apt-get install cmake
  - &install-linguist
    run:
      name: Install github-linguist
      command: gem install github-linguist
  - &run-linguist
    run:
      name: Run github-linguist on repository
      command: github-linguist
  - &generate-html-chart
    run:
      name: Run script that generates html chart file
      command: ./scripts/chart.sh
  - &move-chart-file
    run:
      name: Moving generated chart file to artifacts directory
      command: mv chart.html /tmp/
  - &store-artifact
    store_artifacts:
      path: /tmp/chart.html

defaults: &defaults
  docker:
    - image: circleci/ruby

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - <<: *install-cmake
      - <<: *install-linguist
      - <<: *run-linguist
      - <<: *generate-html-chart
      - <<: *move-chart-file
      - <<: *store-artifact
